version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+asyncmy://root:your_root_password@db:3306/doctor_app
      - SECRET_KEY=supersecret
      - ALGORITHM=HS256

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: doctor_app
      MYSQL_USER: user
      MYSQL_PASSWORD: your_root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
